package com.example.flight_reservation_app_01.util;

import java.io.FileOutputStream;
import java.util.Date;

import org.springframework.stereotype.Component;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Component
public class PDFgenerator {
   	
    public void generatePDF(String filePath, String name, String emailId, String phone, String operatingAirline, String departureDate, String departureCity, String arrivalCity, long resId) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            addMetaData(document);
            addTitleAndTable(document, name, emailId, phone, operatingAirline, departureDate, departureCity, arrivalCity, resId);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }
    
    private static void addTitleAndTable(Document document, String name, String emailId, String phone, String operatingAirline, String departureDate, String departureCity, String arrivalCity, long resId) 
    		throws DocumentException {
        Paragraph preface = new Paragraph();

        preface.add(new Paragraph("Flight Booking Deatils:"));
        
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph("Report generated by: " + "Flight Reservation Company: " + new Date()));
        
        preface.add(new Paragraph("\nReservation Id: " + resId));
        
        document.add(preface);
        document.add(Chunk.NEWLINE);
        
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);

        PdfPCell c1 = new PdfPCell(new Phrase("Passenger Details"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        c1.setColspan(2);
        table.addCell(c1);

        table.addCell("Passenger Name:");
        table.addCell(name);
        table.addCell("Email Id:");
        table.addCell(emailId);
        table.addCell("Phone Num:");
        table.addCell(phone);

        // Adding Table to document        
        document.add(table);
        
        
        document.add(Chunk.NEWLINE);
        document.add(Chunk.NEWLINE);
        
        PdfPTable table1 = new PdfPTable(2);
        table1.setWidthPercentage(100);
        
        PdfPCell c2 = new PdfPCell(new Phrase("Flights Details"));
        c2.setHorizontalAlignment(Element.ALIGN_CENTER);
        c2.setColspan(2);
        table1.addCell(c2);
        
        table1.addCell("Operating Airlines:");
//        table1.addCell(new Phrase(new Chunk("Captain")));
        table1.addCell(operatingAirline);
        table1.addCell("Departure Date:");
        table1.addCell(departureDate);
        table1.addCell("Departure City:");
        table1.addCell(departureCity);
        table1.addCell("Arrival City:");
        table1.addCell(arrivalCity);
        
        // Adding Table to document   
        
        document.add(table1);
        
    }

//			@Component
//			public class PDFgenerator {
//			    private static String FILE = "C:/Users/hp/Desktop/java/Captain.pdf";
//			    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
//			            Font.BOLD);
//			    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
//			            Font.NORMAL, BaseColor.RED);
//			    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
//			            Font.BOLD);
//			    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
//			            Font.BOLD);
//			
//			    public void generatePDF(String filePath, String name, String emailId, String phone) {
//			        try {
//			            Document document = new Document();
//			            PdfWriter.getInstance(document, new FileOutputStream(filePath));
//			            document.open();
//			//            addMetaData(document);
//			            addTitleAndTable(document, name, emailId, phone);
//			            document.close();
//			        } catch (Exception e) {
//			            e.printStackTrace();
//			        }
//			    }
//			
//			    // iText allows to add metadata to the PDF which can be viewed in your Adobe
//			    // Reader
//			    // under File -> Properties
//			//    private static void addMetaData(Document document) {
//			//        document.addTitle("My first PDF");
//			//        document.addSubject("Using iText");
//			//        document.addKeywords("Java, PDF, iText");
//			//        document.addAuthor("Lars Vogel");
//			//        document.addCreator("Lars Vogel");
//			//    }
//			
//			    
//			    private static void addTitleAndTable(Document document, String name, String emailId, String phone)
//			            throws DocumentException {
//			        Paragraph preface = new Paragraph();
//			
//			        preface.add(new Paragraph("Flight Booking Deatils:", catFont));
//			
//			        // Will create: Report generated by: _name, _date
//			        preface.add(new Paragraph(
//			                "Report generated by: " + "Flight Reservation Company: " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
//			                smallBold));
//			
//			        document.add(preface);
//			        document.add(Chunk.NEWLINE);
//			        document.add(Chunk.NEWLINE);
//			        document.add(Chunk.NEWLINE);
//			        document.add(Chunk.NEWLINE);
//			        document.add(Chunk.NEWLINE);
//			        document.add(Chunk.NEWLINE);
//			        
//			        PdfPTable table = new PdfPTable(2);
//			
//			        // t.setBorderColor(BaseColor.GRAY);
//			        // t.setPadding(4);
//			        // t.setSpacing(4);
//			        // t.setBorderWidth(1);
//			
//			        PdfPCell c1 = new PdfPCell(new Phrase("Passenger Detils"));
//			        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
//			        c1.setColspan(2);
//			        table.addCell(c1);
//			
//			//        table.setHeaderRows(1);
//			
//			        table.addCell("Passenger Name:\t");
//			        table.addCell(name);
//			        table.addCell("Email Id:");
//			        table.addCell(emailId);
//			        table.addCell("Phone Num:");
//			        table.addCell(phone);
//			
//			        // Adding Table to document        
//			        document.add(table);                  
//			        
//			        // Closing the document       
//			        document.close();
//			        
//			    }

}